apiVersion: v1
kind: Service
metadata:
  name: observability-demo
  namespace: observability
  labels: {app: observability-demo}
spec:
  selector: {app: observability-demo}
  ports:
  - {name: http, port: 80, targetPort: 8000}
