grafana:
  enabled: true
  adminUser: admin
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
alertmanager:
  enabled: true
